name: Package and release
on:
    push:
        tags:
            - '**'
jobs:
    release:
        runs-on: ubuntu-latest
        env:
            GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
        steps:
            - name: Clone project
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0
            - name: Create Release
              uses: ncipollo/release-action@v1.11.2
            - name: Package and release
              uses: BigWigsMods/packager@v2
